name: nom_du_projet
description: Une nouvelle application Flutter.
publish_to: "none" # Remplacez par 'none' si vous ne souhaitez pas publier ce package.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.24.5"

dependencies:
  animated_custom_dropdown: ^3.1.1
  cinetpay: ^1.0.7
  dio: ^5.7.0
  flutter_inappwebview: ^6.0.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_stripe: ^11.3.0
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  intl: ^0.20.1
  pinput: ^5.0.0
  unicons: ^3.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  textfield_tags: ^3.0.1
  flutter_tags: ^1.0.0-nullsafety.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  get: ^4.6.6
  transparent_image: ^2.0.1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  timeago: ^3.2.2
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  widget_to_marker: ^1.0.6
  loader_overlay: ^4.0.4+1
  file_picker: ^8.1.7
  mime: ^2.0.0
  open_filex: ^4.6.0
  bubble: ^1.2.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.1
  internet_connection_checker: ^3.0.1
  url_launcher: ^6.3.1
  # smart_auth: ^2.0.0

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LOGO-MYE-Dark.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 100
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500
