// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9w6rU18dCRM09tne8C882G9brog5mSQ',
    appId: '1:525902566155:android:f48c97764613a6c920480e',
    messagingSenderId: '525902566155',
    projectId: 'myeapp-chrysalidedev',
    storageBucket: 'myeapp-chrysalidedev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcL14CqxBVFa-ZEpXvbeQ8yk4Fz11dFEk',
    appId: '1:525902566155:ios:381ca385eee1707a20480e',
    messagingSenderId: '525902566155',
    projectId: 'myeapp-chrysalidedev',
    storageBucket: 'myeapp-chrysalidedev.firebasestorage.app',
    androidClientId: '525902566155-s12lr621vq4eni16769hb3cpol13aul6.apps.googleusercontent.com',
    iosClientId: '525902566155-c1721k0n1k4sjcsvdhmhbgmen333hsl2.apps.googleusercontent.com',
    iosBundleId: 'com.chrysalidedev.mye',
  );
}
